[package]
name = "TRACE"
version = "0.1.0"
edition = "2021"

[dependencies]
glium = "0.35.0"
winit = "0.30.4"
glutin-winit = "0.5.0"
image = "0.25.2"
itertools = "0.13.0"
uuid = { version = "1.11.0", features = ["v4"] }
