#version 450 core

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

uniform float time;
uniform uint width;
uniform uint height;
uniform layout(binding=3, rgba8) image2D src;
uniform layout(binding=4, rgba8) image2D dst;


void main() {
    ivec2 pos = ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y);

    /*do stuff here. whatever. mostly empty compute shader for some free space if needed when debugging.*/
}
